# Site settings
name: Arturo Reyes
title: Arturo Reyes| Front End Software Developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: arturoreyes.me
baseurl: ''
email: rs.arturo@icloud.com
cover: //arturreyes.github.io/img/og.png
logo: //arturreyes.github.io/img/emojis/technologist.png
resume: //arturreyes.github.io/resume.pdf
social:
  - title: email
    url: mailto: rs.arturo@icloud.com
  - title: codepen
    url: https://codepen.io/rs-arturo
  - title: github
    url: https://github.com/arturreyes
  - title: linkedin
    url: https://www.linkedin.com/in/arturo-rs

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
